### ISSUE TITLE
Prop Ideas

### ISSUE THREAD

**Issue by nzkfc** [Project-Sloth/ps-props#1]
Some prop ideas, items that a farily common in RP servers as crafting items or common objects used for certain activities like repair kits and lockpicks and such.

Would be nice to get a full vegetable/fruits planting type model set, I know theres a few small packs free on CFX forum, but things like:
- Single lettuce
- row of 3-4 of them
- Row of 8-10 of them

Can be used in scripts, for example ps-drugprocessing if someone wanted to add in a new drug type or similar.

**Comment by MonkeyWhisper** [comment]
@nzkfc If you'd like specific vegetable/fruits send a full list detailed and we can work on it

**Comment by nzkfc** [comment]
So props would be in sets so people can use them in scripts or for YMAP edits and such:
https://i.imgur.com/CfyKZRe.png

Would be handy for some stable props like:
Corn Plant
Lettuce
Tomato Plant
Pumpkins
Potato Plant
Bean Stalk
Wheat
Grape Plant (assume on a wood structure like vanilla)  (not sure if vanilla has these already from vineyard that are flat/oddly shaped)
Onion Plant
Banana Tree?
